name: Publish

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+"

jobs:
  publish:
    if: github.repository == 'rameel/ramstack.structures'
    runs-on: ubuntu-latest
    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: dotnet build -c Release

      - name: Create NuGet Packages
        run: dotnet pack -c Release -o ./nuget --no-build

      - name: Publish NuGet Packages
        run: dotnet nuget push ./nuget/*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --skip-duplicate -s https://api.nuget.org/v3/index.json

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: nuget/*
